apiVersion: v1
kind: Service
metadata:
  name: login-application-service
  labels:
    name: frontend-service
    app: 2-tier-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: 2-tier-app
    name: login
    tier: frontend