apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: 2-tier-app
    name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-db
      tier: backend
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-db
        tier: backend
    spec:
      containers:
      - name: mysql
        image: akshay77/mysql:1.4
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Mind@123
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql-pv-claim
      nodeSelector:
        type: backend
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
