apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: backend-service
    app: 2-tier-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: 2-tier-app
    name: mysql-db
    tier: backend